[Char Widths]
line 0=0123456789
line 1=()/.-%+

DefaultWidth=25 # char width, was 25
AddToAllWidths=0 # for kerning.
DrawExtraPixelsLeft=16
DrawExtraPixelsRight=16
AdvanceExtraPixels=0 #in case the glow cuts off, adjust this. was 0

# make ( and ) narrower, orig is 25
10=16
11=16

# make . and - narrower
13=16
14=20

# give % extra padding
15=40